SRC_URI:append:siena := " \
           file://ntb.scc \
           file://ntb.cfg \
           file://amd_io.cfg \
           file://prof.scc \
           file://prof.cfg \
	  "

SRC_URI:append:turin := " \
           file://ntb.scc \
           file://ntb.cfg \
           file://amd_io.cfg \
           file://prof.scc \
           file://prof.cfg \
           file://sdci.scc \
           file://sdci.cfg \
	  "

SRC_URI:append:e2005 := " \
           file://amd_io.cfg \
           file://prof.cfg \
           file://prof.scc \
           file://gen_io.scc \
           file://asf.scc \
           file://i2c_slave.scc \
          "

